name: Terraform Apply Demo

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  apply:
    runs-on: ubuntu-latest
    concurrency:
      group: terraform-lock-demo
      cancel-in-progress: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0
      - name: Debug AWS credentials
        run: |
          echo "Access Key Length: ${#AWS_ACCESS_KEY_ID}"
          echo "Secret Key Length: ${#AWS_SECRET_ACCESS_KEY}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -lock-timeout=300s
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
